/* ------------------------------------------------------------------
   Export.

   Markdown and plain text are produced in-file. PDF goes through the
   browser's own print pipeline (see 10-print.css) rather than a bundled
   PDF library: no dependency, real selectable text, and it honours the
   user's page size.
   ------------------------------------------------------------------ */

const Exporter = (function(){

  function stamp(){
    const d = new Date();
    return d.getFullYear() + "-" + String(d.getMonth() + 1).padStart(2, "0") + "-" + String(d.getDate()).padStart(2, "0");
  }

  /* ---------------- conversation ---------------- */
  function toMarkdown(c){
    const lines = [];
    lines.push("# " + c.title, "");
    lines.push("*" + Config.assistant.name + " · " + Config.company.name + " · " +
               fmtDateLong(c.ts) + "*", "");
    lines.push("Profile: **" + (S.user ? S.user.name : "") + "** — " + (S.user ? S.user.title : "") +
               " (" + (CLEARANCE[currentClearance()] || {}).label + " access)", "");
    lines.push("---", "");

    c.messages.forEach(function(m){
      if(m.role === "user"){
        lines.push("### " + m.text, "");
        return;
      }
      lines.push(m.text || "", "");
      if(m.sources && m.sources.length){
        lines.push("**Sources**", "");
        m.sources.forEach(function(s){
          lines.push("- [S" + s.n + "] `" + s.id + "` " + s.title +
                     (s.owner ? " — " + s.owner : "") +
                     (s.updated ? ", updated " + s.updated : "") +
                     (s.rev ? ", rev " + s.rev : ""));
        });
        lines.push("");
      }
      if(m.artifact){
        lines.push("**" + Artifacts.label(m.artifact) + ": " + (m.artifact.title || "") + "**", "");
        lines.push(Artifacts.toText(m.artifact), "");
      }
      lines.push("---", "");
    });

    lines.push("", "*Generated by " + Config.product.name + " " + Config.product.version +
               (Config.product.vendor ? " · " + Config.product.vendor : "") + ".*");
    return lines.join("\n");
  }

  function conversation(id){
    closeFloaters();
    const c = id ? S.convos.find(function(x){ return x.id === id; }) : Chat.conversation();
    if(!c || !c.messages.length){ toast("There is nothing to export yet", "warn"); return; }
    downloadBlob(toMarkdown(c), safeName(c.title) + "_" + stamp() + ".md", "text/markdown;charset=utf-8");
    toast("Exported as Markdown", "ok");
  }

  function copyConversation(){
    closeFloaters();
    const c = Chat.conversation();
    if(!c || !c.messages.length){ toast("There is nothing to copy yet", "warn"); return; }
    copyText(toMarkdown(c), "Conversation");
  }

  /* ---------------- print ---------------- */
  function withPrintHeader(title, sub, cls, done){
    const head = document.createElement("div");
    head.className = "print-head";
    head.innerHTML = '<div class="ph-t">' + esc(title) + '</div><div class="ph-m">' + esc(sub) + "</div>";

    const host = cls === "pr-artifact" ? el("panelBody") : el("threadInner");
    host.insertBefore(head, host.firstChild);
    document.body.classList.add(cls);

    const cleanup = function(){
      document.body.classList.remove(cls);
      head.remove();
      window.removeEventListener("afterprint", cleanup);
      if(done) done();
    };
    window.addEventListener("afterprint", cleanup);
    setTimeout(function(){
      window.print();
      /* Safari/Firefox do not always fire afterprint */
      setTimeout(cleanup, 1500);
    }, 60);
  }

  function printThread(){
    closeFloaters();
    const c = Chat.conversation();
    if(!c || !c.messages.length){ toast("There is nothing to print yet", "warn"); return; }
    withPrintHeader(
      c.title,
      Config.company.name + " · " + Config.assistant.name + " · " + fmtDateLong(Date.now()) +
        " · " + (S.user ? S.user.name + ", " + S.user.title : ""),
      "pr-thread"
    );
  }

  function printArtifact(){
    closeFloaters();
    const a = Panel.current();
    if(!a){ toast("Open a visual first", "warn"); return; }
    withPrintHeader(
      a.spec.title || a.title,
      Config.company.name + " · " + fmtDateLong(Date.now()) + " · " + (S.user ? S.user.name : ""),
      "pr-artifact"
    );
  }

  /* ---------------- menus ---------------- */
  function menu(event){
    event.stopPropagation();
    closeFloaters();
    const node = document.createElement("div");
    node.className = "menu";
    node.innerHTML =
      '<div class="menu-head">This conversation</div>' +
      '<button class="menu-item" onclick="Exporter.printThread()">' + Icons.el("share") + "Print / save as PDF</button>" +
      '<button class="menu-item" onclick="Exporter.conversation()">' + Icons.el("download") + "Download Markdown</button>" +
      '<button class="menu-item" onclick="Exporter.copyConversation()">' + Icons.el("copy") + "Copy to clipboard</button>";
    const r = event.currentTarget.getBoundingClientRect();
    placeFloater(node, r.right - 200, r.bottom + 6);
    Icons.hydrate(node);
  }

  function artifactMenu(a){
    closeFloaters();
    const name = safeName(a.spec.title || a.title);
    const node = document.createElement("div");
    node.className = "menu";
    node.innerHTML =
      '<div class="menu-head">' + esc(a.kind === "source" ? "Source document" : Artifacts.label(a.spec)) + "</div>" +
      '<button class="menu-item" onclick="Exporter.printArtifact()">' + Icons.el("share") + "Print / save as PDF</button>" +
      '<button class="menu-item" onclick="Exporter.artifactFile(\'md\',\'' + escJs(name) + '\')">' + Icons.el("doc") + "Download Markdown</button>" +
      '<button class="menu-item" onclick="Exporter.artifactFile(\'txt\',\'' + escJs(name) + '\')">' + Icons.el("file") + "Download text</button>" +
      (a.spec && a.spec.headers ? '<button class="menu-item" onclick="Exporter.artifactFile(\'csv\',\'' + escJs(name) + '\')">' + Icons.el("table") + "Download CSV</button>" : "") +
      (a.spec && a.spec._img ? '<button class="menu-item" onclick="Exporter.artifactImage()">' + Icons.el("image") + "Download image</button>" : "");
    const btn = $(".panel-head .ib:nth-child(3)") || el("panelBody");
    const r = btn.getBoundingClientRect();
    placeFloater(node, r.left - 150, r.bottom + 6);
    Icons.hydrate(node);
  }

  function artifactFile(kind, name){
    closeFloaters();
    const a = Panel.current();
    if(!a) return;
    if(kind === "csv"){
      const rows = [a.spec.headers].concat(a.spec.rows || []);
      const csv = rows.map(function(r){
        return (r || []).map(function(cell){
          const v = String(cell == null ? "" : cell);
          return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
        }).join(",");
      }).join("\r\n");
      downloadBlob("﻿" + csv, name + "_" + stamp() + ".csv", "text/csv;charset=utf-8");
    }else{
      const text = Panel.asText();
      downloadBlob(text, name + "_" + stamp() + (kind === "md" ? ".md" : ".txt"),
                   kind === "md" ? "text/markdown;charset=utf-8" : "text/plain;charset=utf-8");
    }
    toast("Downloaded", "ok");
  }

  function artifactImage(){
    closeFloaters();
    const a = Panel.current();
    if(!a || !a.spec._img) return;
    const link = document.createElement("a");
    link.href = a.spec._img;
    link.download = safeName(a.spec.title || "image") + ".png";
    document.body.appendChild(link); link.click(); link.remove();
  }

  return {
    conversation: conversation, copyConversation: copyConversation,
    printThread: printThread, printArtifact: printArtifact,
    menu: menu, artifactMenu: artifactMenu, artifactFile: artifactFile, artifactImage: artifactImage,
    toMarkdown: toMarkdown,
  };
})();
